### ISSUE TITLE
Issues on today's data?

### ISSUE THREAD

**Issue by covid-19-stats** [victorvicpal/COVID19_es#10]
Hi,
Did you have trouble recovering data of today from the [PDF](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_75_COVID-19.pdf)?

I saw they added some * and other characters on some data to indicate asymptomatic cases, maybe this issue troubled your automatic data recovery process?

Here is the [file for today](https://covid-19-stats.info/data/COVID_es_14_04_2020.csv) (in the format i used to recover it from your git) .. just in case you need a quick upload.

Thanks

**Comment by victorvicpal** [comment]
Yes, I have had some issues with it.
I'm a bit in a rush with work but I'll try to fix it by night.
Sorry :(

**Comment by victorvicpal** [comment]
I just pushed the data. I found the error but I could not fix it properly.
I will open a new issue in order to fix it.
