### ISSUE TITLE
Missing LaRioja

### ISSUE THREAD

**Issue by covid-19-stats** [victorvicpal/COVID19_es#15]
FYI, LaRioja data is missing in daily data files and final data file since 16/04...
I did not notice it until today when I updated from your git (since 16/04 i have been constructing the file manually)

**Comment by victorvicpal** [comment]
Thanks!
I will fix it asap

**Comment by victorvicpal** [comment]
Fixed! :)

**Comment by victorvicpal** [comment]
Hi!
New changes in the PDF, I will need some time to adapt the code again :(

Sorry

**Comment by victorvicpal** [comment]
I was able to push the new data but I'm gonna wait a bit till I change the whole script.
I'm not sure if the PDF would change it again...
