### ISSUE TITLE
Why are there negative numbers in new daily cases

### ISSUE THREAD

**Issue by dimarkov** [victorvicpal/COVID19_es#18]
Thanks for this repo, very useful and detailed data. I am trying to understand why one can have 
negative values for daily cases ('nuevos'). 

The problem that I am getting is that if one sums over all regions, and looks into national data, 
on 2020-04-24 one gets -10000 new cases. What happened there? And how should the negative 
values per region be interpreted?

**Comment by victorvicpal** [comment]
Thanks for pointing out this error.
It should not be negative, instead of that for each negative number zero should appear.
I'll fix it asap.

**Comment by victorvicpal** [comment]
I've changed the script so the negative values won't show again

**Comment by dimarkov** [comment]
Excellent! Thank you for the prompt response.
