### ISSUE TITLE
Change in Graphs.ipynb

### ISSUE THREAD

**Issue by PedroVelez** [victorvicpal/COVID19_es#2]
Creo que en Graphs.ipynb en "data = pd.read_csv('../data/csv_data/data/dataCOVID19_es.csv')" debería ser data = pd.read_csv('../data/final_data/dataCOVID19_es.csv')

**Comment by victorvicpal** [comment]
Muchas gracias Pedro :)
He cambiado el path.

**Comment by PedroVelez** [comment]
le he añado un ajsute a una curva tipo logísitca: 

https://github.com/PedroVelez/COVID19_es/blob/master/notebooks/LogisticCurve.ipynb

por si quiere añadirlo, no manejo mucho lo de fork/PR

**Comment by victorvicpal** [comment]
Gracias Pedro!
Lo añadiré con gusto :)

Muchas gracias por colaborar

**Comment by PedroVelez** [comment]
Los codigos del ajuste a una curva logística son de https://github.com/LucaAngioloni/fit-COVID19, yo los adapte para la lectura de tus datos, que se actualizan antes que los del https://github.com/CSSEGISandData/COVID-19.git
