### ISSUE TITLE
Data in the days without report

### ISSUE THREAD

**Issue by PedroVelez** [victorvicpal/COVID19_es#7]
I have noticed that report _Actualizacion_38_COVID-19.pdf_ was released on the 06/03/2020, and report _Actualizacion_39_COVID-19_ on the 09/03/2020. Accordingly in the folder *csv_data* there are not files for the days 07/03 and 08/03. However in the file *dataCOVID19_es.cnv* there is data in the 07/03 and 08/03, for all the regions, is this linear interpolation?. Thanks

**Comment by victorvicpal** [comment]
Yes, I actually did linear interpolation because of this gap.
You can check it in `src/join_data.py`
Anyway, I should try to document all these things properly.
Thanks for the advice

**Comment by PedroVelez** [comment]
I would suggest not to do any interpolation, at least in the **dataCOVID19_es.cnv** file, or fill in the gaps with _not a number_ values. Maybe you can keep **dataCOVID19_es.cnv**  as the raw data and create a**dataCOVID19_es_interp.cnv**  with the interpolated version.

Moreover, in this particular case, linear interpolation is not the best choice, since at the begging the number of cases was doubling every two days. 
thanks a lot 

Thanks anyway.

**Comment by victorvicpal** [comment]
Agree Pedro.
I will change the issue type to "invalid". I think is better to leave the gaps as they are.
I did it at the beginning when data was scarce, I think it's better to change it.

Thank you for helping me. These days I've been a bit lazy with the repo.

**Comment by victorvicpal** [comment]
Therefore I will fix it asap

**Comment by victorvicpal** [comment]
I think it's fixed.
Could you check it?

**Comment by PedroVelez** [comment]
Thanks!, yes it is working properly. Later today or tomorrow I'll PR an update with the fits, since  I have modified the corresponding notebook to take into account the NaNs.

**Comment by victorvicpal** [comment]
Thanks Pedro!
I close it then
